src/TranLe.PhapY.Web/Areas/Admin/Models/Layout/FooterViewModel.cs
using TranLe.PhapY.Sessions.Dto;

namespace TranLe.PhapY.Web.Areas.Admin.Models.Layout
{
    public class FooterViewModel
    {
        public GetCurrentLoginInformationsOutput LoginInformations { get; set; }

        public string GetProductNameWithEdition()
        {
            var productName = "PhapY";

            if (LoginInformations.Tenant != null && LoginInformations.Tenant.EditionDisplayName != null)
            {
                productName += " " + LoginInformations.Tenant.EditionDisplayName;
            }

            return productName;
        }
    }
}

src/TranLe.PhapY.Web/Areas/Admin/Models/Layout/RightSideBarViewModel.cs
using TranLe.PhapY.Configuration.Ui;

namespace TranLe.PhapY.Web.Areas.Admin.Models.Layout
{
    public class RightSideBarViewModel
    {
        public UiThemeInfo CurrentTheme { get; set; }
    }
}

src/TranLe.PhapY.Web/Areas/Admin/Models/Layout/SidebarViewModel.cs
using Abp.Application.Navigation;

namespace TranLe.PhapY.Web.Areas.Admin.Models.Layout
{
    public class SidebarViewModel
    {
        public UserMenu Menu { get; set; }

        public string CurrentPageName { get; set; }
    }
}

src/TranLe.PhapY.Web/Areas/Admin/Controllers/LayoutController.cs
using System.Linq;
using System.Web.Mvc;
using Abp.Application.Navigation;
using Abp.Configuration;
using Abp.Configuration.Startup;
using Abp.Localization;
using Abp.Runtime.Session;
using Abp.Threading;
using Abp.Web.Mvc.Authorization;
using TranLe.PhapY.Configuration;
using TranLe.PhapY.Configuration.Ui;
using TranLe.PhapY.Sessions;
using TranLe.PhapY.Web.Areas.Admin.Models.Layout;
using TranLe.PhapY.Web.Areas.Admin.Startup;
using TranLe.PhapY.Web.Controllers;
using TranLe.PhapY.Web.Models.Layout;
using TranLe.PhapY.Web.Session;
using HeaderViewModel = TranLe.PhapY.Web.Areas.Admin.Models.Layout.HeaderViewModel;

namespace TranLe.PhapY.Web.Areas.Admin.Controllers
{
    [AbpMvcAuthorize]
    public class LayoutController : PhapYControllerBase
    {
        private readonly IPerRequestSessionCache _sessionCache;
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly IMultiTenancyConfig _multiTenancyConfig;
        private readonly ILanguageManager _languageManager;

        public LayoutController(
            IPerRequestSessionCache sessionCache, 
            IUserNavigationManager userNavigationManager, 
            IMultiTenancyConfig multiTenancyConfig,
            ILanguageManager languageManager)
        {
            _sessionCache = sessionCache;
            _userNavigationManager = userNavigationManager;
            _multiTenancyConfig = multiTenancyConfig;
            _languageManager = languageManager;
        }

        [ChildActionOnly]
        public PartialViewResult Header()
        {
            var headerModel = new HeaderViewModel
            {
                LoginInformations = AsyncHelper.RunSync(() => _sessionCache.GetCurrentLoginInformationsAsync()),
                Languages = _languageManager.GetLanguages(),
                CurrentLanguage = _languageManager.CurrentLanguage,
                IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled,
                IsImpersonatedLogin = AbpSession.ImpersonatorUserId.HasValue
            };

            return PartialView("_Header", headerModel);
        }

        [ChildActionOnly]
        public PartialViewResult Sidebar(string currentPageName = "")
        {
            var sidebarModel = new SidebarViewModel
            {
                Menu = AsyncHelper.RunSync(() => _userNavigationManager.GetMenuAsync(MpaNavigationProvider.MenuName, AbpSession.ToUserIdentifier())),
                CurrentPageName = currentPageName
            };

            return PartialView("_Sidebar", sidebarModel);
        }

        [ChildActionOnly]
        public PartialViewResult Footer()
        {
            var footerModel = new FooterViewModel
            {
                LoginInformations = AsyncHelper.RunSync(() => _sessionCache.GetCurrentLoginInformationsAsync())
            };

            return PartialView("_Footer", footerModel);
        }

        [ChildActionOnly]
        public PartialViewResult ChatBar()
        {
            return PartialView("_ChatBar");
        }

        [ChildActionOnly]
        public PartialViewResult TenantCustomCss()
        {
            var sessionInfo = AsyncHelper.RunSync(() => _sessionCache.GetCurrentLoginInformationsAsync());

            return PartialView("_TenantCustomCss", new TenantCustomCssViewModel
            {
                CustomCssId = sessionInfo.Tenant?.CustomCssId
            });
        }
        [ChildActionOnly]
        public PartialViewResult RightSideBar()
        {
            var themeName = SettingManager.GetSettingValue(AppSettingNames.UiTheme);

            var viewModel = new RightSideBarViewModel
            {
                CurrentTheme = UiThemes.All.FirstOrDefault(t => t.CssClass == themeName.ToString())
            };

            return PartialView("_RightSideBar", viewModel);
        }
    }
}

src/TranLe.PhapY.Web/Controllers/LayoutController.cs
using System.Web.Mvc;
using Abp.Application.Navigation;
using Abp.Configuration;
using Abp.Configuration.Startup;
using Abp.Domain.Uow;
using Abp.Localization;
using Abp.MultiTenancy;
using Abp.Runtime.Session;
using Abp.Threading;
using TranLe.PhapY.Configuration;
using TranLe.PhapY.MultiTenancy;
using TranLe.PhapY.Web.Models.Layout;
using TranLe.PhapY.Web.MultiTenancy;
using TranLe.PhapY.Web.Navigation;
using TranLe.PhapY.Web.Session;

namespace TranLe.PhapY.Web.Controllers
{
    /// <summary>
    /// Layout for 'front end' pages.
    /// </summary>
    public class LayoutController : PhapYControllerBase
    {
        private readonly IPerRequestSessionCache _sessionCache;
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly IMultiTenancyConfig _multiTenancyConfig;
        private readonly ILanguageManager _languageManager;
        private readonly ITenancyNameFinder _tenancyNameFinder;
        private readonly IUnitOfWorkManager _unitOfWorkManager;
        private readonly TenantManager _tenantManager;

        public LayoutController(
            IPerRequestSessionCache sessionCache,
            IUserNavigationManager userNavigationManager,
            IMultiTenancyConfig multiTenancyConfig,
            ILanguageManager languageManager,
            ITenancyNameFinder tenancyNameFinder,
            IUnitOfWorkManager unitOfWorkManager,
            TenantManager tenantManager)
        {
            _sessionCache = sessionCache;
            _userNavigationManager = userNavigationManager;
            _multiTenancyConfig = multiTenancyConfig;
            _languageManager = languageManager;
            _tenancyNameFinder = tenancyNameFinder;
            _unitOfWorkManager = unitOfWorkManager;
            _tenantManager = tenantManager;
        }

        [ChildActionOnly]
        public PartialViewResult Header(string currentPageName = "")
        {
            var headerModel = new HeaderViewModel();

            if (AbpSession.UserId.HasValue)
            {
                headerModel.LoginInformations = AsyncHelper.RunSync(() => _sessionCache.GetCurrentLoginInformationsAsync());
            }

            headerModel.Languages = _languageManager.GetLanguages();
            headerModel.CurrentLanguage = _languageManager.CurrentLanguage;

            headerModel.Menu = AsyncHelper.RunSync(() => _userNavigationManager.GetMenuAsync(FrontEndNavigationProvider.MenuName, AbpSession.ToUserIdentifier()));
            headerModel.CurrentPageName = currentPageName;

            headerModel.IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled;
            headerModel.TenantRegistrationEnabled = SettingManager.GetSettingValue<bool>(AppSettings.TenantManagement.AllowSelfRegistration);

            return PartialView("~/Views/Layout/_Header.cshtml", headerModel);
        }

        [ChildActionOnly]
        public PartialViewResult TenantCustomCss()
        {
            var tenancyName = _tenancyNameFinder.GetCurrentTenancyNameOrNull();
            if (string.IsNullOrEmpty(tenancyName))
            {
                if (AbpSession.UserId.HasValue)
                {
                    var sessionInfo = AsyncHelper.RunSync(() => _sessionCache.GetCurrentLoginInformationsAsync());
                    return PartialView("_TenantCustomCss", new TenantCustomCssViewModel
                    {
                        CustomCssId = sessionInfo.Tenant?.CustomCssId
                    });
                }

                return PartialView("_TenantCustomCss", new TenantCustomCssViewModel
                {
                    CustomCssId = null
                });
            }

            using (_unitOfWorkManager.Begin())
            {
                using (_unitOfWorkManager.Current.SetTenantId(null))
                {
                    var tenant = _tenantManager.FindByTenancyName(tenancyName);
                    return PartialView("_TenantCustomCss", new TenantCustomCssViewModel
                    {
                        CustomCssId = tenant?.CustomCssId
                    });
                }
            }
        }

        [ChildActionOnly]
        public PartialViewResult AppLogo(string appPath, int width = 168, int height = 33)
        {
            ViewBag.TenantCustomLogoWidth = width;
            ViewBag.TenantCustomLogoHeight = height;

            var tenancyName = _tenancyNameFinder.GetCurrentTenancyNameOrNull();
            if (string.IsNullOrEmpty(tenancyName))
            {
                if (AbpSession.TenantId.HasValue)
                {
                    using (_unitOfWorkManager.Begin())
                    {
                        using (_unitOfWorkManager.Current.SetTenantId(null))
                        {
                            var tenant = _tenantManager.FindById(AbpSession.GetTenantId());
                            SetLogoUrlForTenant(appPath, tenant);
                        }
                    }
                }
                else
                {
                    ViewBag.TenantCustomLogoUrl = appPath + "Common/Images/app-logo-on-light.png";
                }
            }
            else
            {
                using (_unitOfWorkManager.Begin())
                {
                    using (_unitOfWorkManager.Current.SetTenantId(null))
                    {
                        var tenant = _tenantManager.FindByTenancyName(tenancyName);
                        SetLogoUrlForTenant(appPath, tenant);
                    }
                }
            }

            return PartialView("~/Views/Account/_AppLogo.cshtml");
        }

        private void SetLogoUrlForTenant(string appPath, Tenant tenant)
        {
            ViewBag.TenantCustomLogoUrl = tenant != null && tenant.LogoId.HasValue
                ? appPath + "TenantCustomization/GetLogo"
                : appPath + "Common/Images/app-logo-on-light.png";
        }
    }
}

src/TranLe.PhapY.Web/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Threading.Tasks;
using System.Web.Mvc;
using Abp;
using Abp.Auditing;
using Abp.Domain.Uow;
using Abp.Extensions;
using Abp.IO.Extensions;
using Abp.Runtime.Session;
using Abp.UI;
using Abp.Web.Models;
using Abp.Web.Mvc.Authorization;
using TranLe.PhapY.Authorization.Users;
using TranLe.PhapY.Friendships;
using TranLe.PhapY.IO;
using TranLe.PhapY.Net.MimeTypes;
using TranLe.PhapY.Storage;

namespace TranLe.PhapY.Web.Controllers
{
    [AbpMvcAuthorize]
    public class ProfileController : PhapYControllerBase
    {
        private readonly UserManager _userManager;
        private readonly IBinaryObjectManager _binaryObjectManager;
        private readonly IAppFolders _appFolders;
        private readonly IFriendshipManager _friendshipManager;

        public ProfileController(
            UserManager userManager,
            IBinaryObjectManager binaryObjectManager,
            IAppFolders appFolders,
            IFriendshipManager friendshipManager)
        {
            _userManager = userManager;
            _binaryObjectManager = binaryObjectManager;
            _appFolders = appFolders;
            _friendshipManager = friendshipManager;
        }

        [DisableAuditing]
        public async Task<FileResult> GetProfilePicture()
        {
            var user = await _userManager.GetUserByIdAsync(AbpSession.GetUserId());
            if (user.ProfilePictureId == null)
            {
                return GetDefaultProfilePicture();
            }

            return await GetProfilePictureById(user.ProfilePictureId.Value);
        }

        [DisableAuditing]
        public async Task<FileResult> GetProfilePictureById(string id = "")
        {
            if (id.IsNullOrEmpty())
            {
                return GetDefaultProfilePicture();
            }

            return await GetProfilePictureById(Guid.Parse(id));
        }

        [DisableAuditing]
        [UnitOfWork]
        public virtual async Task<FileResult> GetFriendProfilePictureById(long userId, int? tenantId, string id = "")
        {
            if (id.IsNullOrEmpty() ||
                _friendshipManager.GetFriendshipOrNull(AbpSession.ToUserIdentifier(), new UserIdentifier(tenantId, userId)) == null)
            {
                return GetDefaultProfilePicture();
            }

            using (CurrentUnitOfWork.SetTenantId(tenantId))
            {
                return await GetProfilePictureById(Guid.Parse(id));
            }
        }

        //TODO: DELETE not used action!!!
        [UnitOfWork]
        public virtual async Task<JsonResult> ChangeProfilePicture()
        {
            try
            {
                //Check input
                if (Request.Files.Count <= 0 || Request.Files[0] == null)
                {
                    throw new UserFriendlyException(L("ProfilePicture_Change_Error"));
                }

                var file = Request.Files[0];

                if (file.ContentLength > 30720) //30KB.
                {
                    throw new UserFriendlyException(L("ProfilePicture_Warn_SizeLimit"));
                }

                //Get user
                var user = await _userManager.GetUserByIdAsync(AbpSession.GetUserId());

                //Delete old picture
                if (user.ProfilePictureId.HasValue)
                {
                    await _binaryObjectManager.DeleteAsync(user.ProfilePictureId.Value);
                }

                //Save new picture
                var storedFile = new BinaryObject(AbpSession.TenantId, file.InputStream.GetAllBytes());
                await _binaryObjectManager.SaveAsync(storedFile);

                //Update new picture on the user
                user.ProfilePictureId = storedFile.Id;

                //Return success
                return Json(new AjaxResponse());
            }
            catch (UserFriendlyException ex)
            {
                //Return error message
                return Json(new AjaxResponse(new ErrorInfo(ex.Message)));
            }
        }

        public JsonResult UploadProfilePicture()
        {
            try
            {
                //Check input
                if (Request.Files.Count <= 0 || Request.Files[0] == null)
                {
                    throw new UserFriendlyException(L("ProfilePicture_Change_Error"));
                }

                var file = Request.Files[0];

                if (file.ContentLength > 1048576) //1MB.
                {
                    throw new UserFriendlyException(L("ProfilePicture_Warn_SizeLimit"));
                }

                //Check file type & format
                var fileImage = Image.FromStream(file.InputStream);
                var acceptedFormats = new List<ImageFormat>
                {
                    ImageFormat.Jpeg, ImageFormat.Png, ImageFormat.Gif
                };

                if (!acceptedFormats.Contains(fileImage.RawFormat))
                {
                    throw new ApplicationException("Uploaded file is not an accepted image file !");
                }

                //Delete old temp profile pictures
                AppFileHelper.DeleteFilesInFolderIfExists(_appFolders.TempFileDownloadFolder, "userProfileImage_" + AbpSession.GetUserId());

                //Save new picture
                var fileInfo = new FileInfo(file.FileName);
                var tempFileName = "userProfileImage_" + AbpSession.GetUserId() + fileInfo.Extension;
                var tempFilePath = Path.Combine(_appFolders.TempFileDownloadFolder, tempFileName);
                file.SaveAs(tempFilePath);

                using (var bmpImage = new Bitmap(tempFilePath))
                {
                    return Json(new AjaxResponse(new { fileName = tempFileName, width = bmpImage.Width, height = bmpImage.Height }));
                }
            }
            catch (UserFriendlyException ex)
            {
                return Json(new AjaxResponse(new ErrorInfo(ex.Message)));
            }
        }

        private FileResult GetDefaultProfilePicture()
        {
            return File(Server.MapPath("~/Common/Images/default-profile-picture.png"), MimeTypeNames.ImagePng);
        }

        private async Task<FileResult> GetProfilePictureById(Guid profilePictureId)
        {
            var file = await _binaryObjectManager.GetOrNullAsync(profilePictureId);
            if (file == null)
            {
                return GetDefaultProfilePicture();
            }

            return File(file.Bytes, MimeTypeNames.ImageJpeg);
        }
    }
}

src/TranLe.PhapY.Web/Areas/Admin/Views/Layout/_Footer.cshtml
@using TranLe.PhapY
@model TranLe.PhapY.Web.Areas.Admin.Models.Layout.FooterViewModel
    @{
        Layout = null;
    }
    <div class="page-footer-inner">
        <span class="text-muted">
            <small>
                @Model.GetProductNameWithEdition() <br/>
                v@(AppVersionHelper.Version) [@AppVersionHelper.ReleaseDate.ToString("yyyyMMdd")]
            </small>
        </span>
    </div>
    <div class="scroll-to-top">
        <i class="icon-arrow-up"></i>
    </div>

src/TranLe.PhapY.Web/Areas/Admin/Views/Layout/_Header.cshtml
@using Abp.MultiTenancy
@using Abp.Timing
@using TranLe.PhapY.Features
@model TranLe.PhapY.Web.Areas.Admin.Models.Layout.HeaderViewModel
@{
    Layout = null;
}
<div class="page-header-inner">
    <div class="page-logo">
        <a href="@Url.Action("Index", "Home", new {area = string.Empty})" target="_blank">
            <img id="AppLogo" src="@Model.GetLogoUrl(ApplicationPath)" alt="logo" class="logo-default" width="168" height="33" />
        </a>
        <div class="menu-toggler sidebar-toggler">
            <i class="fa fa-bars" aria-hidden="true"></i>
            <!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
        </div>
    </div>
    <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
    </a>
    <div class="page-top">
        <div class="top-menu">
            <ul class="nav navbar-nav pull-right">
                @if (Model.Languages.Count > 1)
                {
                    <li class="dropdown dropdown-language">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                            <i class="@Model.CurrentLanguage.Icon"></i>
                            <span class="langname">
                                @Model.CurrentLanguage.DisplayName
                            </span>
                            <i class="fa fa-angle-down"></i>
                        </a>
                        <ul class="dropdown-menu">
                            @foreach (var language in Model.Languages.Where(language => language.Name != Model.CurrentLanguage.Name))
                            {
                                <li>
                                    <a href="~/AbpLocalization/ChangeCulture?cultureName=@language.Name&returnUrl=@Request.Path">
                                        <i class="@language.Icon"></i> @language.DisplayName
                                    </a>
                                </li>
                            }
                        </ul>
                    </li>
                }

                <!-- BEGIN NOTIFICATION DROPDOWN -->
                <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                @*<li class="dropdown dropdown-extended dropdown-notification dropdown-dark" id="header_notification_bar">

                </li>*@
                <!-- END NOTIFICATION DROPDOWN -->
                @*<li class="separator hide"> </li>*@

                <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                <li class="dropdown dropdown-user dropdown-dark">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true" title="@(Model.IsImpersonatedLogin ? L("YouCanBackToYourAccount") : "")">
                        <span class="username username-hide-on-mobile">
                            @if (Model.IsImpersonatedLogin)
                            {
                                <i class="icon-action-undo font-red-sunglo"></i>
                            }
                            @Html.Raw(Model.GetShownLoginName())
                        </span>
                        <img id="HeaderProfilePicture" alt="" class="img-circle" src="@Url.Action("GetProfilePicture", "Profile", new {area = string.Empty})?t=@Clock.Now.Ticks.ToString()" />
                    </a>
                    <ul class="dropdown-menu dropdown-menu-default">
                        @*@if (Model.IsImpersonatedLogin)
                        {
                            <li>
                                <a id="UserProfileBackToMyAccountButton" href="#"><i class="icon-action-undo"></i> <strong>@L("BackToMyAccount")</strong></a>
                            </li>
                            <li class="divider"></li>
                        }
                        <li id="RecentlyUsedLinkedUsers" class="dropdown-submenu">
                            <a href=""><i class="icon-link"></i> @L("LinkedAccounts")</a>
                        </li>

                        <li class="divider"></li>*@

                        <li>
                            <a id="UserProfileChangePasswordLink" href="#"><i class="icon-key"></i> @L("ChangePassword")</a>
                        </li>
                        @*<li>
                            <a id="ShowLoginAttemptsLink" href="#"><i class="icon-shield"></i> @L("LoginAttempts")</a>
                        </li>*@
                        <li>
                            <a id="UserProfileChangePictureLink" href="#"><i class="icon-user"></i> @L("ChangeProfilePicture")</a>
                        </li>
                        <li>
                            <a id="UserProfileMySettingsLink" href="#"><i class="icon-settings"></i> @L("MySettings")</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="@Url.Action("Logout", "Account", new {area = string.Empty})"><i class="icon-logout"></i> @L("Logout")</a>
                        </li>
                    </ul>
                </li>

                @*@if (AbpSession.MultiTenancySide == MultiTenancySides.Host || IsFeatureEnabled(AppFeatures.ChatFeature))
                {
                    <!-- BEGIN QUICK SIDEBAR TOGGLER -->
                    <li class="dropdown dropdown-extended quick-sidebar-toggler">
                        <span class="sr-only">Toggle Quick Sidebar</span>
                        <i class="icon-speech"></i>
                        <span id="UnreadChatMessageCount" class="badge badge-danger hidden">0</span>
                    </li>
                    <!-- END QUICK SIDEBAR TOGGLER -->
                }*@
                <li class="pull-right">
                    <a href="javascript:void(0);" class="js-right-sidebar" data-close="true">
                        <i class="material-icons">more_vert</i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
@*<script id="linkedAccountsSubMenuTemplate" type="x-tmpl-mustache">
    {{#items}}
    <li class="submenu">
        <a href="" data-user-id="{{id}}" data-tenant-id="{{tenantId}}" class="recently-linked-user">
            {{shownUserName}}
        </a>
    </li>
    {{/items}}
    {{#hasLinkedUsers}}
    <li class="divider"></li>
    {{/hasLinkedUsers}}
    <li class="submenu">
        <a href="" id="ManageLinkedAccountsLink">
            <i class="icon-settings"></i> @L("ManageAccounts")
        </a>
    </li>
</script>
<script id="headerNotificationBarTemplate" type="x-tmpl-mustache">
    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
        <i class="icon-bell"></i>
        {{#unreadCount}}
        <span class="badge badge-danger"> {{unreadCount}} </span>
        {{/unreadCount}}
    </a>
    <ul class="dropdown-menu" id="UserNotificationDropdown">
        <li class="external notifications-header">
            <div class="text-left">
                {{#unreadCount}}
                <a href="" id="setAllNotificationsAsReadLink">@L("SetAllAsRead")</a>
                {{/unreadCount}}
                <a id="openNotificationSettingsModalLink" class="pull-right" href="">@L("Settings")</a>
            </div>
        </li>
        <li>
            <ul class="dropdown-menu-list">
                {{#notifications}}
                <li>
                    <a href="{{url}}" class="user-notification-item {{#url}}user-notification-item-clickable{{/url}} {{#isUnread}}user-notification-item-unread{{/isUnread}}">
                        <span class="details">
                            <i class="{{icon}}"></i> {{text}}
                        </span>
                        <div>
                            <span class="notification-time" title="{{time}}">{{timeAgo}}</span>
                            {{#isUnread}}
                            <span>
                                -
                                <span data-notification-id="{{userNotificationId}}" class="set-as-read-text set-notification-as-read">@L("SetAsRead")</span>
                            </span>
                            {{/isUnread}}
                        </div>
                    </a>
                </li>
                {{/notifications}}
            </ul>
            {{^notifications.length}}
            <div class="notification-empty-text">
                @L("ThereIsNoNotification")
            </div>
            {{/notifications.length}}
        </li>
        {{#notifications.length}}
        <li class="external notifications-footer">
            <div class="text-center"><a href="@Url.Action("Index", "Notifications", new {area = "Admin"})">@L("SeeAllNotifications")</a></div>
        </li>
        {{/notifications.length}}
    </ul>
</script>*@

src/TranLe.PhapY.Web/Areas/Admin/Views/Layout/_RightSideBar.cshtml
@using TranLe.PhapY.Configuration.Ui
@model TranLe.PhapY.Web.Areas.Admin.Models.Layout.RightSideBarViewModel
<aside id="rightsidebar" class="right-sidebar">
    <ul class="nav nav-tabs tab-nav-right" role="tablist">
        <li role="presentation" class="active"><a href="#skins" data-toggle="tab">SKINS</a></li>
    </ul>
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade in active in active" id="skins">
            <ul class="demo-choose-skin">
                @foreach (var theme in UiThemes.All)
                {
                    <li data-theme="@theme.CssClass" class="@(Model.CurrentTheme != null ? theme.CssClass == Model.CurrentTheme.CssClass ? "active" : "" : "")">
                        <div class="@theme.CssClass"></div>
                        <span>@theme.Name</span>
                    </li>
                }
            </ul>
        </div>
    </div>
</aside>

src/TranLe.PhapY.Web/Areas/Admin/Views/Layout/_Sidebar.cshtml
@using Abp.Application.Navigation
@using Abp.Collections.Extensions
@using TranLe.PhapY.Web.Areas.Admin.Startup
@model TranLe.PhapY.Web.Areas.Admin.Models.Layout.SidebarViewModel
@{
    @helper RenderUserMenuItem(UserMenuItem menuItem, int menuItemIndex, bool rootLevel)
    {
        <li class="@(menuItemIndex == 0 && rootLevel ? "start" : "") @(menuItem.IsMenuActive(Model.CurrentPageName) ? "active" : "")">
            @if (menuItem.Items.IsNullOrEmpty())
            {
                <a href="@menuItem.CalculateUrl(ApplicationPath)">
                    <i class="@menuItem.Icon"></i>
                    <span class="title">@menuItem.DisplayName</span>
                </a>
            }
            else
            {
                <a href="javascript:;" class="auto">
                    <i class="@menuItem.Icon"></i>
                    <span class="title">@menuItem.DisplayName</span>
                    <span class="arrow"></span>
                </a>
                <ul class="sub-menu">
                    @for (var i = 0; i < menuItem.Items.Count; i++)
                    {
                        var childMenuItem = menuItem.Items[i];
                        @RenderUserMenuItem(childMenuItem, i, false)
                    }
                </ul>
            }
        </li>
    }
}
<div class="page-sidebar navbar-collapse collapse">
    <!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
    <!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
    <!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
    <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
    <!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
    <!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
    <ul class="page-sidebar-menu" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
        @for (var i = 0; i < Model.Menu.Items.Count; i++)
        {
            var menuItem = Model.Menu.Items[i];
            @RenderUserMenuItem(menuItem, i, true);
        }
    </ul>

</div>