src/TranLe.PhapY.Web/Areas/Admin/Models/Layout/FooterViewModel.cs
using TranLe.PhapY.Sessions.Dto;

namespace TranLe.PhapY.Web.Areas.Admin.Models.Layout
{
    public class FooterViewModel
    {
        public GetCurrentLoginInformationsOutput LoginInformations { get; set; }

        public string GetProductNameWithEdition()
        {
            var productName = "PhapY";

            if (LoginInformations.Tenant != null && LoginInformations.Tenant.EditionDisplayName != null)
            {
                productName += " " + LoginInformations.Tenant.EditionDisplayName;
            }

            return productName;
        }
    }
}

src/TranLe.PhapY.Web/Areas/Admin/Models/Layout/HeaderViewModel.cs
using System.Collections.Generic;
using Abp.Localization;
using TranLe.PhapY.Sessions.Dto;

namespace TranLe.PhapY.Web.Areas.Admin.Models.Layout
{
    public class HeaderViewModel
    {
        public GetCurrentLoginInformationsOutput LoginInformations { get; set; }

        public IReadOnlyList<LanguageInfo> Languages { get; set; }

        public LanguageInfo CurrentLanguage { get; set; }

        public bool IsMultiTenancyEnabled { get; set; }

        public bool IsImpersonatedLogin { get; set; }

        public string GetShownLoginName()
        {
            var userName = "<span id=\"HeaderCurrentUserName\">" + LoginInformations.User.UserName + "</span>";

            if (!IsMultiTenancyEnabled)
            {
                return userName;
            }

            return LoginInformations.Tenant == null
                ? ".\\" + userName
                : LoginInformations.Tenant.TenancyName + "\\" + userName;
        }

        public string GetLogoUrl(string appPath)
        {
            if (!IsMultiTenancyEnabled || LoginInformations.Tenant?.LogoId == null)
            {
                return appPath + "Common/Images/app-logo-on-light.png";
            }

            return appPath + "TenantCustomization/GetLogo?id=" + LoginInformations.Tenant.LogoId;
        }
    }
}

src/TranLe.PhapY.Web/Areas/Admin/Models/Layout/RightSideBarViewModel.cs
using TranLe.PhapY.Configuration.Ui;

namespace TranLe.PhapY.Web.Areas.Admin.Models.Layout
{
    public class RightSideBarViewModel
    {
        public UiThemeInfo CurrentTheme { get; set; }
    }
}

src/TranLe.PhapY.Web/Areas/Admin/Models/Layout/SidebarViewModel.cs
using Abp.Application.Navigation;

namespace TranLe.PhapY.Web.Areas.Admin.Models.Layout
{
    public class SidebarViewModel
    {
        public UserMenu Menu { get; set; }

        public string CurrentPageName { get; set; }
    }
}

src/TranLe.PhapY.Web/Models/Layout/HeaderViewModel.cs
using System.Collections.Generic;
using Abp.Application.Navigation;
using Abp.Localization;
using TranLe.PhapY.Sessions.Dto;

namespace TranLe.PhapY.Web.Models.Layout
{
    public class HeaderViewModel
    {
        public GetCurrentLoginInformationsOutput LoginInformations { get; set; }

        public IReadOnlyList<LanguageInfo> Languages { get; set; }

        public LanguageInfo CurrentLanguage { get; set; }

        public UserMenu Menu { get; set; }

        public string CurrentPageName { get; set; }

        public bool IsMultiTenancyEnabled { get; set; }

        public bool TenantRegistrationEnabled { get; set; }

        public string GetShownLoginName()
        {
            if (!IsMultiTenancyEnabled)
            {
                return LoginInformations.User.UserName;
            }

            return LoginInformations.Tenant == null
                ? ".\\" + LoginInformations.User.UserName
                : LoginInformations.Tenant.TenancyName + "\\" + LoginInformations.User.UserName;
        }
    }
}

src/TranLe.PhapY.Web/Models/Layout/TenantCustomCssViewModel.cs
using System;

namespace TranLe.PhapY.Web.Models.Layout
{
    public class TenantCustomCssViewModel
    {
        public Guid? CustomCssId { get; set; }
    }
}

src/TranLe.PhapY.Web/Areas/Admin/Controllers/LayoutController.cs
using System.Linq;
using System.Web.Mvc;
using Abp.Application.Navigation;
using Abp.Configuration;
using Abp.Configuration.Startup;
using Abp.Localization;
using Abp.Runtime.Session;
using Abp.Threading;
using Abp.Web.Mvc.Authorization;
using TranLe.PhapY.Configuration;
using TranLe.PhapY.Configuration.Ui;
using TranLe.PhapY.Sessions;
using TranLe.PhapY.Web.Areas.Admin.Models.Layout;
using TranLe.PhapY.Web.Areas.Admin.Startup;
using TranLe.PhapY.Web.Controllers;
using TranLe.PhapY.Web.Models.Layout;
using TranLe.PhapY.Web.Session;
using HeaderViewModel = TranLe.PhapY.Web.Areas.Admin.Models.Layout.HeaderViewModel;

namespace TranLe.PhapY.Web.Areas.Admin.Controllers
{
    [AbpMvcAuthorize]
    public class LayoutController : PhapYControllerBase
    {
        private readonly IPerRequestSessionCache _sessionCache;
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly IMultiTenancyConfig _multiTenancyConfig;
        private readonly ILanguageManager _languageManager;

        public LayoutController(
            IPerRequestSessionCache sessionCache, 
            IUserNavigationManager userNavigationManager, 
            IMultiTenancyConfig multiTenancyConfig,
            ILanguageManager languageManager)
        {
            _sessionCache = sessionCache;
            _userNavigationManager = userNavigationManager;
            _multiTenancyConfig = multiTenancyConfig;
            _languageManager = languageManager;
        }

        [ChildActionOnly]
        public PartialViewResult Header()
        {
            var headerModel = new HeaderViewModel
            {
                LoginInformations = AsyncHelper.RunSync(() => _sessionCache.GetCurrentLoginInformationsAsync()),
                Languages = _languageManager.GetLanguages(),
                CurrentLanguage = _languageManager.CurrentLanguage,
                IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled,
                IsImpersonatedLogin = AbpSession.ImpersonatorUserId.HasValue
            };

            return PartialView("_Header", headerModel);
        }

        [ChildActionOnly]
        public PartialViewResult Sidebar(string currentPageName = "")
        {
            var sidebarModel = new SidebarViewModel
            {
                Menu = AsyncHelper.RunSync(() => _userNavigationManager.GetMenuAsync(MpaNavigationProvider.MenuName, AbpSession.ToUserIdentifier())),
                CurrentPageName = currentPageName
            };

            return PartialView("_Sidebar", sidebarModel);
        }

        [ChildActionOnly]
        public PartialViewResult Footer()
        {
            var footerModel = new FooterViewModel
            {
                LoginInformations = AsyncHelper.RunSync(() => _sessionCache.GetCurrentLoginInformationsAsync())
            };

            return PartialView("_Footer", footerModel);
        }

        [ChildActionOnly]
        public PartialViewResult ChatBar()
        {
            return PartialView("_ChatBar");
        }

        [ChildActionOnly]
        public PartialViewResult TenantCustomCss()
        {
            var sessionInfo = AsyncHelper.RunSync(() => _sessionCache.GetCurrentLoginInformationsAsync());

            return PartialView("_TenantCustomCss", new TenantCustomCssViewModel
            {
                CustomCssId = sessionInfo.Tenant?.CustomCssId
            });
        }
        [ChildActionOnly]
        public PartialViewResult RightSideBar()
        {
            var themeName = SettingManager.GetSettingValue(AppSettingNames.UiTheme);

            var viewModel = new RightSideBarViewModel
            {
                CurrentTheme = UiThemes.All.FirstOrDefault(t => t.CssClass == themeName.ToString())
            };

            return PartialView("_RightSideBar", viewModel);
        }
    }
}

src/TranLe.PhapY.Web/Controllers/ApplicationController.cs
using System.Web.Mvc;
using Abp.Auditing;
using Abp.Web.Mvc.Authorization;

namespace TranLe.PhapY.Web.Controllers
{
    [AbpMvcAuthorize]
    public class ApplicationController : PhapYControllerBase
    {
        [DisableAuditing]
        public ActionResult Index()
        {
            /* Enable next line to redirect to Multi-Page Application */
            /* return RedirectToAction("Index", "Home", new {area = "Admin"}); */

            return RedirectToAction("Index", "Home", new {area = "Admin"});
        }
    }
}

src/TranLe.PhapY.Web/Controllers/TenantRegistrationController.cs
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Abp.Authorization;
using Abp.Authorization.Users;
using Abp.Configuration;
using Abp.Configuration.Startup;
using Abp.Domain.Uow;
using Abp.UI;
using Abp.Zero.Configuration;
using TranLe.PhapY.Configuration;
using TranLe.PhapY.Debugging;
using TranLe.PhapY.Web.Models.TenantRegistration;
using Recaptcha.Web;
using Recaptcha.Web.Mvc;
using Abp.Extensions;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using TranLe.PhapY.Authorization;
using TranLe.PhapY.Authorization.Users;
using TranLe.PhapY.Editions;
using TranLe.PhapY.MultiTenancy;
using TranLe.PhapY.Notifications;
using TranLe.PhapY.Web.Auth;

namespace TranLe.PhapY.Web.Controllers
{
    public class TenantRegistrationController : PhapYControllerBase
    {
        private readonly IMultiTenancyConfig _multiTenancyConfig;
        private readonly TenantManager _tenantManager;
        private readonly UserManager _userManager;
        private readonly LogInManager _logInManager;
        private readonly EditionManager _editionManager;
        private readonly IAppNotifier _appNotifier;
        private readonly AbpLoginResultTypeHelper _abpLoginResultTypeHelper;

        private IAuthenticationManager AuthenticationManager => HttpContext.GetOwinContext().Authentication;

        public TenantRegistrationController(
            IMultiTenancyConfig multiTenancyConfig,
            TenantManager tenantManager,
            EditionManager editionManager,
            IAppNotifier appNotifier,
            UserManager userManager,
            AbpLoginResultTypeHelper abpLoginResultTypeHelper,
            LogInManager logInManager)
        {
            _multiTenancyConfig = multiTenancyConfig;
            _tenantManager = tenantManager;
            _editionManager = editionManager;
            _appNotifier = appNotifier;
            _userManager = userManager;
            _abpLoginResultTypeHelper = abpLoginResultTypeHelper;
            _logInManager = logInManager;
        }

        public ActionResult Index()
        {
            CheckTenantRegistrationIsEnabled();

            ViewBag.UseCaptcha = UseCaptchaOnRegistration();
            ViewBag.PasswordComplexitySetting = SettingManager.GetSettingValue(AppSettings.Security.PasswordComplexity).Replace("\"","");

            return View();
        }

        [HttpPost]
        [UnitOfWork]
        public virtual async Task<ActionResult> Register(TenantRegistrationViewModel model)
        {
            try
            {
                CheckTenantRegistrationIsEnabled();

                if (UseCaptchaOnRegistration())
                {
                    var recaptchaHelper = this.GetRecaptchaVerificationHelper();
                    if (recaptchaHelper.Response.IsNullOrEmpty())
                    {
                        throw new UserFriendlyException(L("CaptchaCanNotBeEmpty"));
                    }

                    if (recaptchaHelper.VerifyRecaptchaResponse() != RecaptchaVerificationResult.Success)
                    {
                        throw new UserFriendlyException(L("IncorrectCaptchaAnswer"));
                    }
                }

                //Getting host-specific settings
                var isNewRegisteredTenantActiveByDefault = await SettingManager.GetSettingValueForApplicationAsync<bool>(AppSettings.TenantManagement.IsNewRegisteredTenantActiveByDefault);
                var isEmailConfirmationRequiredForLogin = await SettingManager.GetSettingValueForApplicationAsync<bool>(AbpZeroSettingNames.UserManagement.IsEmailConfirmationRequiredForLogin);
                var defaultEditionIdValue = await SettingManager.GetSettingValueForApplicationAsync(AppSettings.TenantManagement.DefaultEdition);
                int? defaultEditionId = null;

                if (!string.IsNullOrEmpty(defaultEditionIdValue) && (await _editionManager.FindByIdAsync(Convert.ToInt32(defaultEditionIdValue)) != null))
                {
                    defaultEditionId = Convert.ToInt32(defaultEditionIdValue);
                }

                CurrentUnitOfWork.SetTenantId(null);

                var tenantId = await _tenantManager.CreateWithAdminUserAsync(
                  model.TenancyName,
                  model.Name,
                  model.AdminPassword,
                  model.AdminEmailAddress,
                  null,
                  isNewRegisteredTenantActiveByDefault,
                  defaultEditionId,
                  false,
                  true);

                ViewBag.UseCaptcha = UseCaptchaOnRegistration();

                var tenant = await _tenantManager.GetByIdAsync(tenantId);
                await _appNotifier.NewTenantRegisteredAsync(tenant);

                CurrentUnitOfWork.SetTenantId(tenant.Id);

                var user = await _userManager.FindByNameAsync(AbpUserBase.AdminUserName);

                //Directly login if possible
                if (tenant.IsActive && user.IsActive && (user.IsEmailConfirmed || !isEmailConfirmationRequiredForLogin))
                {
                    var loginResult = await GetLoginResultAsync(user.UserName, model.AdminPassword, tenant.TenancyName);

                    if (loginResult.Result == AbpLoginResultType.Success)
                    {
                        await SignInAsync(loginResult.User, loginResult.Identity);
                        return Redirect(Url.Action("Index", "Application"));
                    }

                    Logger.Warn("New registered user could not be login. This should not be normally. login result: " + loginResult.Result);
                }

                return View("RegisterResult", new TenantRegisterResultViewModel
                {
                    TenancyName = model.TenancyName,
                    Name = model.Name,
                    UserName = AbpUserBase.AdminUserName,
                    EmailAddress = model.AdminEmailAddress,
                    IsActive = isNewRegisteredTenantActiveByDefault,
                    IsEmailConfirmationRequired = isEmailConfirmationRequiredForLogin
                });
            }
            catch (UserFriendlyException ex)
            {
                ViewBag.UseCaptcha = UseCaptchaOnRegistration();
                ViewBag.ErrorMessage = ex.Message;

                return View("Index", model);
            }
        }

        private bool IsSelfRegistrationEnabled()
        {
            return SettingManager.GetSettingValueForApplication<bool>(AppSettings.TenantManagement.AllowSelfRegistration);
        }

        private void CheckTenantRegistrationIsEnabled()
        {
            if (!IsSelfRegistrationEnabled())
            {
                throw new UserFriendlyException(L("SelfTenantRegistrationIsDisabledMessage_Detail"));
            }

            if (!_multiTenancyConfig.IsEnabled)
            {
                throw new UserFriendlyException(L("MultiTenancyIsNotEnabled"));
            }
        }

        private bool UseCaptchaOnRegistration()
        {
            if (DebugHelper.IsDebug)
            {
                return false;
            }

            return SettingManager.GetSettingValueForApplication<bool>(AppSettings.TenantManagement.UseCaptchaOnRegistration);
        }

        private async Task<AbpLoginResult<Tenant, User>> GetLoginResultAsync(string usernameOrEmailAddress, string password, string tenancyName)
        {
            var loginResult = await _logInManager.LoginAsync(usernameOrEmailAddress, password, tenancyName);

            switch (loginResult.Result)
            {
                case AbpLoginResultType.Success:
                    return loginResult;
                default:
                    throw _abpLoginResultTypeHelper.CreateExceptionForFailedLoginAttempt(loginResult.Result, usernameOrEmailAddress, tenancyName);
            }
        }

        private async Task SignInAsync(User user, ClaimsIdentity identity = null, bool rememberMe = false)
        {
            if (identity == null)
            {
                identity = await _userManager.CreateIdentityAsync(user, DefaultAuthenticationTypes.ApplicationCookie);
            }

            AuthenticationManager.SignOutAllAndSignIn(identity, rememberMe);
        }
    }
}

src/TranLe.PhapY.Web/Views/Layout/_Footer.cshtml
@using Abp.Timing
    <!-- BEGIN FOOTER -->
<div class="footer">
    <div class="container">
        <div class="row">
            <!-- BEGIN COPYRIGHT -->
            <div class="col-md-6 col-sm-6 padding-top-10">
                @Clock.Now.Year © PhapY. ALL Rights Reserved. <a href="javascript:;">Privacy Policy</a> | <a href="javascript:;">Terms of Service</a>
            </div>
            <!-- END COPYRIGHT -->
            <!-- BEGIN PAYMENTS -->
            <div class="col-md-6 col-sm-6">
                <ul class="social-footer list-unstyled list-inline pull-right">
                    <li><a href="javascript:;"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="javascript:;"><i class="fa fa-google-plus"></i></a></li>
                    <li><a href="javascript:;"><i class="fa fa-dribbble"></i></a></li>
                    <li><a href="javascript:;"><i class="fa fa-linkedin"></i></a></li>
                    <li><a href="javascript:;"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="javascript:;"><i class="fa fa-skype"></i></a></li>
                    <li><a href="javascript:;"><i class="fa fa-github"></i></a></li>
                    <li><a href="javascript:;"><i class="fa fa-youtube"></i></a></li>
                    <li><a href="javascript:;"><i class="fa fa-dropbox"></i></a></li>
                </ul>
            </div>
            <!-- END PAYMENTS -->
        </div>
    </div>
</div>
<!-- END FOOTER -->

src/TranLe.PhapY.Web/Views/Layout/_Header.cshtml
@using Abp.Application.Navigation
@using Abp.Collections.Extensions
@using Abp.Extensions
@using TranLe.PhapY.Web.Views
@model TranLe.PhapY.Web.Models.Layout.HeaderViewModel
@helper ShowMenuItemRecursively(UserMenuItem menuItem, int currentLevel)
{
    <li class="@(menuItem.Name == Model.CurrentPageName ? "active" : "") @(menuItem.Items.IsNullOrEmpty() ? "" : (currentLevel == 0 ? "dropdown" : "dropdown-submenu"))">
        @if (menuItem.Items.IsNullOrEmpty())
        {
            if (!menuItem.Url.IsNullOrEmpty())
            {
                <a href="@(UrlChecker.IsRooted(menuItem.Url) ? menuItem.Url : (ApplicationPath + menuItem.Url))">@menuItem.DisplayName</a>
            }
            else
            {
                <a href="@ApplicationPath">@menuItem.DisplayName</a>
            }
        }
        else
        {
            <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="javascript:;">
                @menuItem.DisplayName
            </a>
            <ul class="dropdown-menu">
                @foreach (var childMenuItem in menuItem.Items)
                {
                    @ShowMenuItemRecursively(childMenuItem, currentLevel + 1)
                }
            </ul>
        }
    </li>
}
<div class="pre-header">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6 additional-shop-info">
                <ul class="list-unstyled list-inline">
                    <li><i class="fa fa-phone"></i><span>+1 456 6717</span></li>
                    <li><i class="fa fa-envelope-o"></i><span>info@mydomain.com</span></li>
                </ul>
            </div>
            <div class="col-md-6 col-sm-6 additional-nav">
                <ul class="list-unstyled list-inline pull-right">
                    @if (Model.Languages.Count > 1)
                    {
                        <li>
                            <div id="LanguageDropDown" class="btn-group dropdown">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" data-delay="1000" data-close-others="true"><i class="@Model.CurrentLanguage.Icon"></i> @Model.CurrentLanguage.DisplayName <i class="fa fa-angle-down"></i></button>
                                <ul class="dropdown-menu" role="menu">
                                    @foreach (var language in Model.Languages)
                                    {
                                        if (Model.CurrentLanguage.Name == language.Name)
                                        {
                                            continue;
                                        }

                                        <li class="language-menu-item">
                                            <a href="@Url.Action("ChangeCulture", "AbpLocalization")?cultureName=@(language.Name)&returnUrl=@Request.Path"><i class="@language.Icon"></i> <span>@language.DisplayName</span></a>
                                        </li>
                                    }
                                </ul>
                            </div>
                        </li>
                    }
                    @if (Model.LoginInformations == null && Model.IsMultiTenancyEnabled && Model.TenantRegistrationEnabled)
                    {
                        <li>
                            <a href="@Url.Action("Index", "TenantRegistration")">@L("NewTenant")</a>
                        </li>
                    }
                    <li>
                        @if (Model.LoginInformations != null)
                        {
                            <a href="@Url.Action("Index", "Application")">@Model.GetShownLoginName() (@L("GoToApplication"))</a>
                        }
                        else
                        {
                            <a href="@Url.Action("Login", "Account")">@L("LogIn")</a>
                        }
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="header">
    <div class="container">
        <a class="site-logo" href="@Url.Action("Index", "Home")">
            @Html.Action("AppLogo", "Layout", new { area = "", appPath = ApplicationPath, width = 168, height = 33 })
        </a>
        <a href="javascript:void(0);" class="mobi-toggler"><i class="fa fa-bars"></i></a>
        <div class="header-navigation pull-right font-transform-inherit">
            <ul>
                @foreach (var menuItem in @Model.Menu.Items)
                {
                    @ShowMenuItemRecursively(menuItem, 0)
                }
            </ul>
        </div>
    </div>
</div>

src/TranLe.PhapY.Web/Views/Layout/_Layout.cshtml
@using System.Web.Optimization
@using Abp.Web.Mvc.Extensions
@using TranLe.PhapY.Localization
@{
    SetAntiForgeryCookie();
}
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" dir=@(CultureHelper.IsRtl ? "rtl" : "")>
<!--<![endif]-->
<head>
    <meta charset="utf-8">
    <title>PhapY</title>

    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    @* Fill these meta tags upon your project specification *@
    <meta content="PhapY" name="description">
    <meta content="PhapY" name="keywords">
    <meta content="PhapY" name="author">

    @* You can enable and fill these lines according to documentation on http://ogp.me/
        <meta property="og:site_name" content="-CUSTOMER VALUE-">
        <meta property="og:title" content="-CUSTOMER VALUE-">
        <meta property="og:description" content="-CUSTOMER VALUE-">
        <meta property="og:type" content="website">
        <meta property="og:image" content="-CUSTOMER VALUE-">
        <meta property="og:url" content="-CUSTOMER VALUE-">*@

    <link rel="shortcut icon" href="~/favicon.ico">

    <link href="~/Content/fonts-open-sans.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/fonts-ptsans-narrow.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/fonts-sourcesans-pro.css" rel="stylesheet" type="text/css" />

    @Styles.Render("~/Bundles/Frontend/libs/css" + (CultureHelper.IsRtl ? "RTL" : ""))
    @RenderSection("Styles", false)
    @Html.Action("TenantCustomCss", "Layout", new { area = "" })
    @Styles.Render("~/Bundles/Frontend/metronic/css" + (CultureHelper.IsRtl ? "RTL" : ""))
    @Styles.Render("~/Bundles/Common/css")

    @Html.IncludeStyle("~/Views/Layout/layout.css")

    <script type="text/javascript">
        @* This is used to get the application's root path from javascript.
        It's useful if you're running application in a virtual directory under IIS. *@
        var abp = abp || {}; abp.appPath = '@ApplicationPath';
    </script>

</head>
<body class="corporate">

    @Html.Action("Header", "Layout", new { currentPageName = ViewBag.CurrentPageName })

    <div class="main">
        <div class="container">
            @RenderBody()
        </div>
    </div>

    @Html.Partial("~/Views/Layout/_Footer.cshtml")

    <!--[if lt IE 9]>
        <script src="~/libs/respond/respond.min.js"></script>
    <![endif]-->

    @Scripts.Render("~/Bundles/Frontend/libs/js")

    <script type="text/javascript">
        abp.localization.defaultSourceName = '@LocalizationSourceName';
    </script>

    <!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
    <script src="~/AbpScripts/GetScripts" type="text/javascript"></script>

    @Scripts.Render("~/Bundles/Frontend/metronic/js")

    @Scripts.Render("~/Bundles/Common/js")

    <script type="text/javascript">
        $(function () {
            Layout.init();
        });
    </script>

    @RenderSection("Scripts", false)

</body>

</html>

src/TranLe.PhapY.Web/Views/Layout/_TenantCustomCss.cshtml
@model TranLe.PhapY.Web.Models.Layout.TenantCustomCssViewModel
@if (Model.CustomCssId != null)
{
    <link id="TenantCustomCss" rel="stylesheet" href="@Url.Action("GetCustomCss", "TenantCustomization", new { area = string.Empty, id = Model.CustomCssId.Value })" />
}